GoodNewsTask/Controllers/ArticlesConductorFilterController.cs
using GoodNewsTask.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoodNewsTask.Controllers
{
    public class ArticlesConductorFilterController : Controller
    {
        public int ratingAticle { get; set; }
        public ParserForSputnik _parserSputnik { get; set; } = new ParserForSputnik();
        public ParserForLenta _parserLenta { get; set; } = new ParserForLenta();
        public ParserForOnliner _parserOnliner { get; set; } = new ParserForOnliner();
        private readonly NewsContext _db; //подключение ArticlesFilterController к БД

        public ArticlesConductorFilterController(NewsContext enteredContext)
        {
            _db = enteredContext;
        }

        [HttpGet]
        [Route("[controller]/[action]")] //для Swagger-а
        [Authorize(Roles = "Admin")]
        public void Filtering()//ожидай появления пустой страницы после выполнения работы!!!
        {
            List<Article> articles = _parserOnliner.ParseXmlForLinks("https://www.onliner.by/feed"); //Создан лист с новостями из Onliner.by
            articles.AddRange(_parserLenta.ParseXmlForLinks("https://lenta.ru/rss/articles")); //Добавляем лист с новостями из Lenta.ru
            articles.AddRange(_parserSputnik.ParseXmlForLinks("https://sputnik.by/sitemap.xml")); //Добавляем лист с новостями из Sputnik.by
            
            
            //Если глючит или тормозит, закомменируй 
            //articles.AddRange(_parserLenta.ParseXmlForLinks("https://lenta.ru/rss/articles"));
            //или
            //articles.AddRange(_parserSputnik.ParseXmlForLinks("https://sputnik.by/sitemap.xml"));

            #region Список слов для определения рейтинга статей
            List<KeyValuePair<string, int>> ratingWords = new List<KeyValuePair<string, int>>
        {
            new KeyValuePair<string, int>("agonises", -3),
            new KeyValuePair<string, int>("apeshit", -3),
            new KeyValuePair<string, int>("Awaits", -1),
            new KeyValuePair<string, int>("bamboozles", -2),
            new KeyValuePair<string, int>("bankster", -3),
            new KeyValuePair<string, int>("bereaves", -2),
            new KeyValuePair<string, int>("bereaving", -2),
            new KeyValuePair<string, int>("brilliances", 3),
            new KeyValuePair<string, int>("cocksuckers", -5),
            new KeyValuePair<string, int>("consolable", 2),
            new KeyValuePair<string, int>("criminates", -3),
            new KeyValuePair<string, int>("dejecting", -2),
            new KeyValuePair<string, int>("dejects", -2),
            new KeyValuePair<string, int>("Dilligence", 2),
            new KeyValuePair<string, int>("dipshit", -3),
            new KeyValuePair<string, int>("disconsolation", -2),
            new KeyValuePair<string, int>("exasparate", -2),
            new KeyValuePair<string, int>("exhilarates", 3),
            new KeyValuePair<string, int>("frikin", -2),
            new KeyValuePair<string, int>("FTW", 3),
            new KeyValuePair<string, int>("fuckface", -4),
            new KeyValuePair<string, int>("fuckhead", -4),
            new KeyValuePair<string, int>("fucktard", -4),
            new KeyValuePair<string, int>("FUD", -3),
            new KeyValuePair<string, int>("fuked", -4),
            new KeyValuePair<string, int>("fuking", -4),
            new KeyValuePair<string, int>("goofiness", -2),
            new KeyValuePair<string, int>("greenwasher", -3),
            new KeyValuePair<string, int>("greenwashers", -3),
            new KeyValuePair<string, int>("Greenwashing", -3),
            new KeyValuePair<string, int>("hahahah", 3),
            new KeyValuePair<string, int>("haplessness", -2),
            new KeyValuePair<string, int>("heavyhearted", -2),
            new KeyValuePair<string, int>("humerous", 3),
            new KeyValuePair<string, int>("impedingly", -2),
            new KeyValuePair<string, int>("incensing", -2),
            new KeyValuePair<string, int>("inediable", -2),
            new KeyValuePair<string, int>("Infract", -2),
            new KeyValuePair<string, int>("infracted", -2),
            new KeyValuePair<string, int>("infracts", -2),
            new KeyValuePair<string, int>("intransigency", -2),
            new KeyValuePair<string, int>("Lawl", 3),
            new KeyValuePair<string, int>("LMAO", 4),
            new KeyValuePair<string, int>("LMFAO", 4),
            new KeyValuePair<string, int>("LOLOL", 4),
            new KeyValuePair<string, int>("lololol", 4),
            new KeyValuePair<string, int>("lolololol", 4),
            new KeyValuePair<string, int>("Lool", 3),
            new KeyValuePair<string, int>("Loool", 3),
            new KeyValuePair<string, int>("looool", 3),
            new KeyValuePair<string, int>("MEMORIAM", -2),
            new KeyValuePair<string, int>("mirthfully", 3),
            new KeyValuePair<string, int>("misclassifies", -2),
            new KeyValuePair<string, int>("misconducted", -2),
            new KeyValuePair<string, int>("misconducting", -2),
            new KeyValuePair<string, int>("misleaded", -3),
            new KeyValuePair<string, int>("misreports", -2),
            new KeyValuePair<string, int>("n00b", -2),
            new KeyValuePair<string, int>("OKS", 2),
            new KeyValuePair<string, int>("optionless", -2),
            new KeyValuePair<string, int>("ostracizes", -2),
            new KeyValuePair<string, int>("oversells", -2),
            new KeyValuePair<string, int>("prblm", -2),
            new KeyValuePair<string, int>("prblms", -2),
            new KeyValuePair<string, int>("Robs", -2),
            new KeyValuePair<string, int>("ROFL", 4),
            new KeyValuePair<string, int>("roflcopter", 4),
            new KeyValuePair<string, int>("ROFLMAO", 4),
            new KeyValuePair<string, int>("romantical", 2),
            new KeyValuePair<string, int>("ROTFL", 4),
            new KeyValuePair<string, int>("rotflmfao", 4),
            new KeyValuePair<string, int>("rotflol", 4),
            new KeyValuePair<string, int>("savange", -2),
            new KeyValuePair<string, int>("savanges", -2),
            new KeyValuePair<string, int>("Secures", 2),
            new KeyValuePair<string, int>("sexistic", -2),
            new KeyValuePair<string, int>("shoody", -2),
            new KeyValuePair<string, int>("singleminded", -2),
            new KeyValuePair<string, int>("stinked", -2),
            new KeyValuePair<string, int>("sueing", -2),
            new KeyValuePair<string, int>("tyrans", -3),
            new KeyValuePair<string, int>("uninvolving", -2),
            new KeyValuePair<string, int>("unreleting", -2),
            new KeyValuePair<string, int>("WINWIN", 3),
            new KeyValuePair<string, int>("Woohoo", 3),
            new KeyValuePair<string, int>("Wooo", 4),
            new KeyValuePair<string, int>("woow", 4),
            new KeyValuePair<string, int>("WOWOW", 4),
            new KeyValuePair<string, int>("wowww", 4),
            new KeyValuePair<string, int>("WTF", -4),
            new KeyValuePair<string, int>("wtff", -4),
            new KeyValuePair<string, int>("wtfff", -4),
            new KeyValuePair<string, int>("XO", 3),
            new KeyValuePair<string, int>("XOXO", 3),
            new KeyValuePair<string, int>("xoxoxo", 4),
            new KeyValuePair<string, int>("xoxoxoxo", 4),
            new KeyValuePair<string, int>("yeees", 2),
            new KeyValuePair<string, int>("абсентеистами", -1),
            new KeyValuePair<string, int>("аварийная сигнализация", -2),
            new KeyValuePair<string, int>("авария", -2),
            new KeyValuePair<string, int>("агрессивность", -2),
            new KeyValuePair<string, int>("агрессивный", -2),
            new KeyValuePair<string, int>("агрессий", -2),
            new KeyValuePair<string, int>("агрессия", -2),
            new KeyValuePair<string, int>("ад", -4),
            new KeyValuePair<string, int>("адекватный", 1),
            new KeyValuePair<string, int>("адский", -2),
            new KeyValuePair<string, int>("акколада", 2),
            new KeyValuePair<string, int>("аккуратность", 2),
            new KeyValuePair<string, int>("актив", 2),
            new KeyValuePair<string, int>("активный", 1),
            new KeyValuePair<string, int>("активы", 2),
            new KeyValuePair<string, int>("акцептование", 2),
            new KeyValuePair<string, int>("акции", 1),
            new KeyValuePair<string, int>("акция протеста", -2),
            new KeyValuePair<string, int>("аллергический", -2),
            new KeyValuePair<string, int>("аллилуйя", 3),
            new KeyValuePair<string, int>("алчный", 2),
            new KeyValuePair<string, int>("альтруистический", 2),
            new KeyValuePair<string, int>("амбивалентный", -1),
            new KeyValuePair<string, int>("амбициозный", 2),
            new KeyValuePair<string, int>("Анжер", -3),
            new KeyValuePair<string, int>("аномалия развития", -2),
            new KeyValuePair<string, int>("антагонистический", -2),
            new KeyValuePair<string, int>("анти", -1),
            new KeyValuePair<string, int>("апатичный", -3),
            new KeyValuePair<string, int>("апатия", -3),
            new KeyValuePair<string, int>("аплодирует", 2),
            new KeyValuePair<string, int>("аплодируют", 2),
            new KeyValuePair<string, int>("аплодисменты", 2),
            new KeyValuePair<string, int>("апокалиптический", -2),
            new KeyValuePair<string, int>("арестованный", -3),
            new KeyValuePair<string, int>("арестовать", -2),
            new KeyValuePair<string, int>("аресты", -2),
            new KeyValuePair<string, int>("атака", -1),
            new KeyValuePair<string, int>("атакующий", -1),
            new KeyValuePair<string, int>("аура", 1),
            new KeyValuePair<string, int>("аферы", -3),

GoodNewsTask/Controllers/RegistrationController.cs
using GoodNewsTask.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace GoodNewsTask.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly NewsContext _db;
        public RegistrationController(NewsContext enteredContext)
        {
            _db = enteredContext;
        }

        //[HttpGet]
        //[AcceptVerbs("Get", "Post")] //ЭТО НАДО БУДЕТ СПРОСИТЬ КАК ДЕЛАТЬ ПРОВЕРКУ ПО СПИСКУ ПОЧТОВЫХ ЯЩИКОВ (см. https://metanit.com/sharp/aspnetmvc/9.3.php )
        //public IActionResult CheckEmail(string enteredEmail)
        //{
        //    if (enteredEmail == "admin@mail.com")
        //    {
        //        return Json(false); //СПРОСИТЬ. Я очень сомневаюсь, что это нужно. Может надо return Context("Такой эл. ящик уже занят"); 
        //    }
        //    return Json(true);//СПРОСИТЬ. Вроде бы логично. Я не знаю, правильно ли так делать? Но мне надо вернуть из этого метода enteredEmail. 

        //}

        [HttpGet]
        [Route("[controller]/[action]")] //для Swagger-а
        [AllowAnonymous]
        public IActionResult Create()
        {
            //await Task.CompletedTask; так не надо делать
            return View(); //писать return await Task.FromResult(View()); не надо 
                           //оформляй View() для регистрации нового пользователя
        }

        [HttpPost]
        [Route("[controller]/[action]")] //для Swagger-а
        //[AllowAnonymous]
        public IActionResult Create(User enteredUser)
		{
            if (string.IsNullOrEmpty(enteredUser.Login)) 
            {
				ModelState.AddModelError("Login", "Не введён Login");
			}
            foreach (var user in _db.Users)
            {
				if (user.Login == enteredUser.Login)
				{
					ModelState.AddModelError("Login", "Такое имя уже кем-то используется");
				}
			}

			if (string.IsNullOrEmpty(enteredUser.Password))
			{
				ModelState.AddModelError("Password", "Не введён Password");
			}
            if (enteredUser.Email == "admin@mail.com")
            {
                ModelState.AddModelError("Email", "Такой e-mail нельзя использовать");
			}
            foreach (var user in _db.Users) 
            {

                if (user.Email == enteredUser.Email)
                {
					ModelState.AddModelError("Email", "Такой e-mail уже кем-то используется");
				}
            }
			if (string.IsNullOrEmpty(enteredUser.Email))
			{
				ModelState.AddModelError("Email", "Не введён Email");
			}
			if (enteredUser.SelectedPositiveLevel <0 || enteredUser.SelectedPositiveLevel >100)
			{
				ModelState.AddModelError("SelectedPositiveLevel", "Значение должно быть больше ноля (но не более 100)");
			}

			if (ModelState.IsValid)
            {
                _db.Users.Add(enteredUser);
                _db.SaveChanges();
				ViewBag.SuccessRegistrationMessage = "Пользователь зарегистрирован";
			}
            if (ModelState.IsValid ==false)
            {
				ViewBag.SuccessRegistrationMessage = "Пользователь НЕ зарегистрирован";
			}
            return View(enteredUser);
        }
    }
}

GoodNewsTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoodNewsTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GoodNewsTask.styles.css" asp-append-version="true" />
    @*Добавленный шрифт из google-fonts*@
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>
<body>
    <header>
       @* Исходный вариант <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Logo.png" alt="LogoBird" style="height: 40px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="InputLoginPassword">InputLoginPassword</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="RestorePasswordAndPositiveLevel">RestorePasswordAndPositiveLevel</a>
                        </li>
                       @* Тут swagger *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="swagger" asp-action="index"><font color="#005fbe"><b>Swagger тут</b></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Display" asp-action="TestHangFireMethod"><font color="#d50be3"><b>Запуск HangFire тут</b></font></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticlesConductorFilter" asp-action="Filtering"><font color="#db1b0b"><b>Скраппинг новостей (около 3 минут думает!)</b></font></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @*Новый navbar*@
        @* Исходный вариант <nav id="navbar2" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        <nav id="navbar2" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/LogoYellow.png" alt="LogoBirdYellow" style="height: 40px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Display" asp-action="ShowArticlesFromDBForGuests">ShowArticlesFromDBForGuests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Display" asp-action="ShowArticlesFromDBForRegisteredUsers">ShowArticlesFromDBForRegisteredUsers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Display" asp-action="ShowArticlesFromDBForAdmin">ShowArticlesFromDBForAdmin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Display" asp-action="ShowUsersFromDBForAdmin">ShowUsersFromDBForAdmin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @* Начало кода по кнопкам для цветовых режимов *@
    <div class="button-container">
        <button class="button buttonMorningMode" onclick="morningModeToggle()">Утренний режим</button>
        <button class="button buttonDayMode" onclick="dayModeToggle()">Дневной режим</button>
        <button class="button buttonEveningMode" onclick="eveningModeToggle()">Вечерний режим</button>
        <button class="button buttonNightMode" onclick="nightModeToggle()">Ночной режим</button>
    </div>
    @* Окончание кода по кнопкам для цветовых режимов *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GoodNewsTask developed by Radevich Anatoliy - <a asp-area="" asp-controller="Home" asp-action="Privacy"><small>А тут у меня часики</small></a>😊
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>